module.exports = [
  {
    item: "pussy",
    price: 100,
    type: "Collectable",
    name: "Pussy",
    emoji: "🐱",
    title: "🐱 Pussy --> 100 mangoes || *Collectable*",
    description: "Get your own pussy cat for 100 mangoes\nㅤ",
  },
  {
    item: "holymango",
    price: 200,
    type: "Collectable",
    name: "Holy Mango",
    emoji: "🥭",
    title: "🥭 Holy Mango --> 200 mangoes || *Collectable*",
    description: "The Holy Mango\nㅤ",
  },
  {
    item: "walletlock",
    price: 350,
    type: "Protection",
    name: "Wallet Lock",
    emoji: "🔑",
    title: "🔑 Wallet Lock --> 350 mangoes || *Protection*",
    description: "Protect the mangoes in your wallet from getting stolen!\nㅤ",
  },
  {
    item: "padlock",
    price: 500,
    type: "Protection",
    name: "Padlock",
    emoji: "🔐",
    title: "🔐 Padlock --> 500 mangoes || *Protection*",
    description: "Protect the mangoes in your bank from getting robbed!\nㅤ",
  },
  {
    item: "betterluck",
    price: 720,
    type: "Luck",
    name: "Better Luck",
    emoji: "❤️‍🔥",
    title: "❤️‍🔥 Better Luck --> 720 mangoes || *Luck*",
    description:
      "Have better luck for 1 day when stealing/robbing/commiting a crime!\nㅤ",
  },
]
